<?php
/**
 * @file
 * tools_catalogue.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function tools_catalogue_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-22e7kRc1V2sl4m5H6bob2YrOnCJkTzHq'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '22e7kRc1V2sl4m5H6bob2YrOnCJkTzHq',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-7qYMvDizpBW0Ph2vhhPLoT15jcHy2pe4'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => '7qYMvDizpBW0Ph2vhhPLoT15jcHy2pe4',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => 'Target audience',
    'visibility' => '0',
  );

  $export['facetapi-Lajhd6MCzUxQwGyRmZf7Vea5gaGMg0LP'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'Lajhd6MCzUxQwGyRmZf7Vea5gaGMg0LP',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-SP1TtsVhkQexXXQewyHW1AYdNf5SiJCf'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'SP1TtsVhkQexXXQewyHW1AYdNf5SiJCf',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-XzyKGq7Eqv1kZFvRfqo0jKZ2gyvMJ9gz'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'XzyKGq7Eqv1kZFvRfqo0jKZ2gyvMJ9gz',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '/resource/tools-catalogue',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => 'sidebar_first',
        'status' => '1',
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '1',
  );

  $export['facetapi-YHcdA3crVelIWd0SAPF23Qdqtt5eQiBH'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'YHcdA3crVelIWd0SAPF23Qdqtt5eQiBH',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-dtVLo1iOtjTPRuirG1TjY1iIzeWTP11s'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'dtVLo1iOtjTPRuirG1TjY1iIzeWTP11s',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-mxDMHKg0rhI0Kfxqt97fD4YID1KZL54L'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'mxDMHKg0rhI0Kfxqt97fD4YID1KZL54L',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => '',
    'visibility' => '0',
  );

  $export['facetapi-nGqxeJ7jhxPhbo07z4B5DAnF3DWreuKa'] = array(
    'cache' => -1,
    'custom' => '0',
    'delta' => 'nGqxeJ7jhxPhbo07z4B5DAnF3DWreuKa',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => '0',
      ),
      'vizz2' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'vizz2',
        'weight' => '0',
      ),
      'vng' => array(
        'region' => 'sidebar_second',
        'status' => '1',
        'theme' => 'vng',
        'weight' => '0',
      ),
    ),
    'title' => 'Standard & format',
    'visibility' => '0',
  );

  return $export;
}
