name = GBIF Simple
description = A simple 3 column layout demonstrating mobile first and Susy. For GBIF Portal.
preview = preview.png
template = gbsimple-layout

; Regions
regions[user]           = User
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[menu]           = Menu
regions[help]           = Help

regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar

regions[footer]         = Footer
regions[static_links]   = Static links
regions[credits]        = Credits

; Stylesheets
stylesheets[all][] = css/layouts/gbsimple/gbsimple.layout.css
