<?php

/**
 * @file
 * gbif_pages.module
 *
 * An important reference post:
 * @see http://chacadwa.com/blog/2012/12/08/override-drupal-7-taxonomy-display-vocabulary
 * @see https://api.drupal.org/api/views/views.module/function/views_embed_view/7
 */
 
/**
 * Implements hook_menu_alter().
 */
function gbif_pages_menu_alter(&$items) {
  $items['taxonomy/term/%taxonomy_term']['page callback'] = 'gbif_pages_taxonomy_term_page';
}

/**
 * Implementation of hook_views_api().
 */
function gbif_pages_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'gbif_pages') . '/views'
  );
}

/**
 * Build custom term pages with associated views.
 * 
 * The logic assumes one view per term page. In case we need to 
 * associate more than one view, we then add a condition and write
 * another custom function which should return $build.
 */
function gbif_pages_taxonomy_term_page($term) {
  $term_view = gbif_pages_term_view_relation();
  if (array_key_exists($term->tid, $term_view)) {

    $uri = entity_uri('taxonomy_term', $term);

    // Set the term path as the canonical URL to prevent duplicate content.
    drupal_add_html_head_link(array('rel' => 'canonical', 'href' => url($uri['path'], $uri['options'])), TRUE);
    // Set the non-aliased path as a default shortlink.
    drupal_add_html_head_link(array('rel' => 'shortlink', 'href' => url($uri['path'], array_merge($uri['options'], array('alias' => TRUE)))), TRUE);

    $build = taxonomy_term_show($term);

    // This is the only deviation from the core function.
    $build['members'] = array('#markup' => views_embed_view($term_view[$term->tid]['view'], $term_view[$term->tid]['display']));
    
  }
  else {
    $build = taxonomy_term_page($term);
  }
  return $build;
}

function gbif_pages_term_view_relation() {
  $term_view = array(
    '566' => array( // newsroom/news
      'view' => 'newsarticles',
      'display' => 'page',
    ), 
    '567' => array( // newsroom/uses
      'view' => 'usesofdatafeaturedarticles',
      'display' => 'latest6',
    ), 
    '569' => array( // newsroom/events
      'view' => 'viewallevents',
      'display' => 'page',
    ),
    '764' => array( // resources/summary
      'view' => 'viewallresources',
      'display' => 'latest5',
    ),     
  );
  return $term_view;
}