<?php

/**
 * @file
 * gbif_pages.module
 *
 * An important reference post:
 * @see http://chacadwa.com/blog/2012/12/08/override-drupal-7-taxonomy-display-vocabulary
 * @see https://api.drupal.org/api/views/views.module/function/views_embed_view/7
 */

/**
 * Implements hook_menu_alter().
 */
function gbif_pages_menu_alter(&$items) {
  $items['taxonomy/term/%taxonomy_term']['page callback'] = 'gbif_pages_taxonomy_term_page';
}

/**
 * Implements hook_block_info_alter().
 */
function gbif_pages_block_info_alter(&$blocks, $theme, $code_blocks) {
  switch ($theme) {
    case 'bvng':
      break;
  }
}

/**
 * Implements hook_library().
 */
function gbif_pages_library() {
  $libraries['gbif_page_widgets'] = array(
    'title' => 'GBIF Widgets',
    'js' => array(
      variable_get('data_portal_base_url') . '/js/widgets.js' => array(
        'type' => 'file',
        'scope' => 'footer',
        'weight' => 20,
      ),
    ),
  );
  return $libraries;
}

/**
 * Implementation of hook_views_api().
 */
function gbif_pages_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'gbif_pages') . '/views'
  );
}

function gbif_pages_views_register() {
	$views = array(
			'newsarticles',
			'usesofdatafeaturedarticles',
			'datausearticles',
			'featurednewsarticles',
			'viewallevents',
			'viewallresources',
	);
	return $views;
}

/**
 * Build custom term pages with associated views.
 *
 * The logic assumes one view per term page. In case we need to
 * associate more than one view, we then add a condition and write
 * another custom function which should return $build.
 */
function gbif_pages_taxonomy_term_page($term) {
  $relation = gbif_pages_term_view_relation();
  if (array_key_exists($term->tid, $relation)) {

    $uri = entity_uri('taxonomy_term', $term);

    // Set the term path as the canonical URL to prevent duplicate content.
    drupal_add_html_head_link(array('rel' => 'canonical', 'href' => url($uri['path'], $uri['options'])), TRUE);
    // Set the non-aliased path as a default shortlink.
    drupal_add_html_head_link(array('rel' => 'shortlink', 'href' => url($uri['path'], array_merge($uri['options'], array('alias' => TRUE)))), TRUE);

    // Every term page has a chance to show the description in taxaNavigation.
    $build = taxonomy_term_show($term);

    // Attach view(s) depending on term-view relations.
    $markup = '';
    $view_count = 0;
    array_walk_recursive($relation[$term->tid], function($value, $key) use (&$view_count) {
    	if ($key == 'view') $view_count++;
    });

    if ($view_count > 1) {
      foreach ($relation[$term->tid] as $view_block) {
        $markup .= "\n";
        $markup .= views_embed_view($view_block['view'], $view_block['display']);
      }
    }
    elseif ($view_count === 1) {
      $markup = views_embed_view($relation[$term->tid]['view'], $relation[$term->tid]['display']);
    }

    // Attach the final result to the page build.
    $build['members'] = array('#markup' => $markup);

  }
  else {
    $build = taxonomy_term_page($term);
  }
  return $build;
}


function gbif_pages_term_view_relation() {
  $relation = array(
    '565' => array( // newsroom/summary
      array(
        'view' => 'featurednewsarticles',
        'display' => 'default',
      ),
      array(
        'view' => 'usesofdatafeaturedarticles',
        'display' => 'latest3',
      ),
      array(
        'view' => 'newsarticles',
        'display' => 'latest3',
      ),
    ),
    '566' => array( // newsroom/news
      'view' => 'newsarticles',
      'display' => 'page',
    ),
    '567' => array( // newsroom/uses
      'view' => 'usesofdatafeaturedarticles',
      'display' => 'latest6',
    ),
    '569' => array( // newsroom/events
      'view' => 'viewallevents',
      'display' => 'current',
    ),
    '764' => array( // resources/summary
    	'view' => 'viewallresources',
    	'display' => 'latest5',
    ),
  );
  return $relation;
}
