<?php

/**
 * Implements hook_menu().
 */
function gbif_catalogue_menu() {
  $items = array();
  $items['admin/config/gbif'] = array(
    'title' => 'GBIF',
    'description' => "Relevant settings that support the Drupal instance runs as the global portal CMS.",
    'position' => 'right',
    'weight' => -10,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/gbif/catalogue'] = array(
    'title' => 'GBIF Catalogue',
    'description' => 'Settings and configuration for the GBIF Catalogue.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('gbif_catalogue_settings_form'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'gbif_catalogue.admin.inc',
  );
  return $items;
}


function gbif_catalogue_definition() {
  // The definition set
  $definitions = array(
    array(
      'name' => 'Purpose',
      'machine_name' => 'orc_purpose',
      'description' => '[ORC] The purpose of the tool',
      'terms' => array('Data digitization', 'Data curation/quality', 'Data publishing', 'Data access/display', 'Data analysis'),
      'weight' => 0
    ),
    array(
      'name' => 'Target audience',
      'machine_name' => 'orc_target_audience',
      'description' => '[ORC] Targeted type of audience. For example, taxonomists or modellers.',
      'terms' => array('Data publishers', 'Data users', 'Nat. Hist. col.', 'Naturalists', 'GBIF Nodes', 'IT specialists', 'Scientists', 'Field biologists', 'Taxonomists', 'Modellers', 'Nat. resource managers', 'Practitioners', 'Software developers', 'Wider audiences'),
      'weight' => 1
    ),
    array(
      'name' => 'Language',
      'machine_name' => 'orc_language',
      'description' => '[ORC] The language(s) for accessing this resource.',
      'terms' => array('Chinese', 'English', 'French', 'Spanish'),
      'weight' => 2
    ),
    array(
      'name' => 'Data type',
      'machine_name' => 'orc_data_type',
      'description' => '[ORC] Applicable data types.',
      'terms' => array('Occurrence data', 'Names and taxonomy', 'Metadata', 'Species information', 'Multimedia data', 'Ecological data'),
      'weight' => 3
    ),
    array(
      'name' => 'Tool type',
      'machine_name' => 'orc_tool_type',
      'description' => '[ORC] In which form the tool is used. For example, desktop or web based.',
      'terms' => array('Desktop tool', 'Online tool', 'Server application', 'Web service', 'Widget', 'Tool set', 'Mobile application'),
      'weight' => 4
    ),
    array(
      'name' => 'Development status',
      'machine_name' => 'orc_development_status',
      'description' => '[ORC] In which phase the development is.',
      'terms' => array('Production ready', 'Beta', 'Alpha / prototype', 'Demo', 'In development'),
      'weight' => 5
    ),
    array(
      'name' => 'Operating system',
      'machine_name' => 'orc_operating_system',
      'description' => '[ORC] On which platform the tool runs.',
      'terms' => array('OS independent', 'MS Windows', 'Mac OS X', 'Linux', 'iOS', 'Android', 'MS Windows ME'),
      'weight' => 6
    ),
    array(
      'name' => 'BI standard',
      'machine_name' => 'orc_bi_standard',
      'description' => '[ORC] Compliance of standard(s).',
      'terms' => array('Darwin Core', 'Darwin Core Archive', 'GBIF Metadata Profile', 'ABCD', 'OGC', 'Dublin Core', 'Plinian Core', 'Audubon Core', 'DELTA', 'SDD', 'RDF', 'SHP', 'KML', 'GML', 'ISO 19115'),
      'weight' => 7
    ),
    array(
      'name' => 'Resource type',
      'machine_name' => 'orc_resource_type',
      'description' => '[ORC] Resource type.',
      'terms' => array('Data resource', 'Digital document', 'Digital file', 'Internet URL', 'Presentation', 'Tool'),
      'weight' => 8
    ),
  );
  
  return $definitions;  
}

function gbif_catalogue_vocabularies_create() {

  $definitions = gbif_catalogue_definition();

  // Insert default vocabularies and initial terms
  foreach ($definitions as $df) {
    $voc = array(
      'name' => $df['name'],
      'machine_name' => $df['machine_name'],
      'description' => $df['description'],
      'hierarchy' => '0',
      'module' => 'taxonomy',
      'weight' => $df['weight'],
      'rdf_mapping' => array(
        'rdftype' => array(
          0 => 'skos:ConceptScheme',
        ),
        'name' => array(
          'predicates' => array(
            0 => 'dc:title',
          ),
        ),
        'description' => array(
          'predicates' => array(
            0 => 'rdfs:comment',
          ),
        ),
      ),
    );

    $voc = (object)$voc;
    taxonomy_vocabulary_save($voc);
    unset($voc);

    // Now populate terms by using the newly created vocabulary
    $voc = taxonomy_vocabulary_machine_name_load($df['machine_name']);
    foreach ($df['terms'] as $termname) {
      $term = new stdClass;
      $term->vid = $voc->vid;
      $term->name = $termname;
      taxonomy_term_save($term);
    }
  }
  
  return t('Vocabularies created.');
}

function gbif_catalogue_vocabularies_delete() {
  $definitions = gbif_catalogue_definition();
  foreach ($definitions as $df) {
    $voc = taxonomy_vocabulary_machine_name_load($df['machine_name']);
    taxonomy_vocabulary_delete($voc->vid);
  }
  return t('Vocabularies deleted.');
}